import { GetStaticProps, GetStaticPaths, GetServerSideProps } from 'next'
import type { NextPage } from 'next'
import Head from 'next/head'
import React, { Fragment, useContext } from 'react'
import { ThemeContext } from 'styled-components'

import Header from '../components/header'
import Hero from '../components/hero'
import Presentation from '../components/whoIAm'
import Studied from '../components/whatIStudied'
import Services from '../components/whatDoIDo'
import Guidelines from '../components/myPrinciples'
import Portifolio from '../components/portifolio'
import Process from '../components/whoIWork'
import Arguments from '../components/goodChoice'
import Testimonials from '../components/sayAboutMe'
import Footer from '../components/footer'

export default function Home({ posts }: any) {
  return (
    <Fragment>
      <Head>
        <title>Home Page</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Hero />
      <Header />
      <Presentation />
      <Studied />
      <Services />
      <Guidelines />
      <Portifolio />
      <Process />
      <Arguments />
      <Testimonials />
      <Footer />
    </Fragment>
  )
}

// This function gets called at build time
export const getStaticProps: GetStaticProps = async () => {
  return {
    props: {
      data: ['Apple', 'Orange', 'Banana']
    }
  }

  // const allPostsData = getSortedPostsData()
  // return {
  //   props: {
  //     allPostsData
  //   }
  // }

  // Call an external API endpoint to get posts
  // const res = await fetch('https://.../posts')
  // const posts = await res.json()

  // // By returning { props: { posts } }, the Blog component
  // // will receive `posts` as a prop at build time
  // return {
  //   props: {
  //     posts,
  //   },
  // }
}
