name: build

on:
  push:
    branches:
      - '*'
      - '!master'
  pull_request:
    branches:
      - '!*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get latest code
        uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Build Project
        run: npm run build
