name: heroku-deploy

on:
  push:
    branches:
      - develop
      - feature/**
      - fix/**
      - refactor/**

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.4.6
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: 'miguelsmuller-site-pessoal'
          heroku_email: 'miguelsmuller@gmail.com'

      - name: Run a one-line script
        run: echo successfully run
