name: firebase-deploy

on:
  push:
    branches:
      - '*'
      - '*/*'
      - '**'

jobs:
  build:
    name: Deploy to Firebase
    runs-on: ubuntu-latest

    steps:
      - name: Get latest code
        uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'

      - name: Install dependencies
        run: npm ci

      - name: Build Project
        run: npm run build

      - name: Deploy Project
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only functions,hosting
        env:
          GCP_SA_KEY: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
