name: Deploy to Preview

on:
  push:
    branches:
      - '*'
      - '!master'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get latest code
        uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      
      - name: Set environment variables
        run: |
          echo '${{ secrets.HYGRAPH_API }}' > ./settings/graphcms.json
          echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}' > $HOME/gcloud.json

      - name: Build Project
        run: npm ci && npm run build

  deploy_preview:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Get latest code
        uses: actions/checkout@v4

      - name: Set environment variables
        run: |
          echo '${{ secrets.HYGRAPH_API }}' > ./settings/graphcms.json
          echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}' > $HOME/gcloud.json

      - name: Install dependencies
        run: npm ci && npm run build

      - name: Deploy to Live
        run: |
          npx firebase-tools experiments:enable webframeworks
          export GOOGLE_APPLICATION_CREDENTIALS=$HOME/gcloud.json && npx firebase-tools hosting:channel:deploy "${{ github.sha }}"

